### ISSUE TITLE
TpSystem - 传送系统 ——功能增加&改善

### ISSUE THREAD

**Issue by yufengya0420** [engsr6982/LLSE_Plugins#21]
## 插件：
TpSystem

## 功能描述：
随机传送的功能能不能加一个以某个特定坐标为中心，选择以圆形范围或矩形范围为标准范围，进行一次以特定格数为半径进行一次随机传送，可以有两种传送模式：1.以中心点在“圆形/矩阵”中随机一个坐标
2.设置半径最小值到边界中随机一个坐标
可以对接ZoneCheck

**Comment by BULANG888888** [comment]
玩家在下界死亡后，弹出返回死亡点选项，点击后就卡了，有没有QQ群，这我发不了视频

**Comment by yufengya0420** [comment]
> 玩家在下界死亡后，弹出返回死亡点选项，点击后就卡了，有没有QQ群，这我发不了视频

你能不能自己建个issue，我这是反馈的一个增加功能，不是反馈bug
